apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: client-authentication

spec:
  clientAuth:
    # the CA certificate is extracted from key `tls.ca` or `ca.crt` of the given secrets.
    secretNames:
      - client-auth-ca
    clientAuthType: RequireAndVerifyClientCert